package tour.rov.profile.entity;

import java.time.LocalDate;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "profile")
public class Profile {
    @Id
    private String id; // ObjectId will be autogenerated for this field

    private LocalDate birthday;

    @Indexed(unique = true)
    private String email;

    private String firstName;

    private Gender gender;

    private String lastName;

    private String password;

    private String imageUrl;

    private ProfileGame profileGame;

    private Message[] messages;

    public Profile() {
    }

    public Profile(String id, LocalDate birthday, String email, String firstName, Gender gender, String lastName,
            String password, String imageUrl, ProfileGame profileGame, Message[] messages) {
        this.id = id;
        this.birthday = birthday;
        this.email = email;
        this.firstName = firstName;
        this.gender = gender;
        this.lastName = lastName;
        this.password = password;
        this.imageUrl = imageUrl;
        this.profileGame = profileGame;
        this.messages = messages;
    }

    public enum Gender {
        Male,
        Female
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public LocalDate getBirthday() {
        return birthday;
    }

    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public ProfileGame getProfileGame() {
        return profileGame;
    }

    public void setProfileGame(ProfileGame profileGame) {
        this.profileGame = profileGame;
    }

    public Message[] getMessages() {
        return messages;
    }

    public void setMessages(Message[] messages) {
        this.messages = messages;
    }

}
